/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-2',
  aws_cognito_identity_pool_id:
    'us-east-2:5aead06b-4ebf-4a45-a6e1-31d42794ccd2',
  aws_cognito_region: 'us-east-2',
  aws_user_pools_id: 'us-east-2_34aOVjx4Z',
  aws_user_pools_web_client_id: '3io57jq39f9chc7o3vlm2ovp47',
  oauth: {},
  aws_cognito_username_attributes: [],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ['EMAIL'],
  aws_cognito_mfa_configuration: 'OFF',
  aws_cognito_mfa_types: ['SMS'],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ['EMAIL'],
  aws_appsync_graphqlEndpoint:
    'https://kdrkrdu6orevlpen7cftut5b6y.appsync-api.us-east-2.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-2',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: 'da2-s3x6nux2ifdvvdk54hbbn33ppa',
  aws_dynamodb_all_tables_region: 'us-east-2',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'User-uk5bmajo2zc7pjck4ht325nenu-staging',
      region: 'us-east-2',
    },
  ],
  aws_cognito_login_mechanisms: ['PREFERRED_USERNAME'],
};

export default awsmobile;
